(() => {
  "use strict";

  const HELP_ITEMS = [
    { key:"scenario", title:"ชื่อ Scenario", category:"1. Scenario", aliases:["ชื่อ Scenario"], definition:"ชื่อชุดสมมติฐานที่กำลังจำลอง ใช้แยก Base case, Recruitment plan, Retention plan หรือกรณีอื่น", unit:"ข้อความ", source:"ผู้วิเคราะห์กำหนดเอง", example:"เชียงราย รพช. 5Y - Base case", origin:"input" },
    { key:"start-year", title:"ปีเริ่มต้น (พ.ศ.)", category:"1. Scenario", aliases:["ปีเริ่มต้น (พ.ศ.)","ปี"], definition:"ปีฐานปีแรกของการพยากรณ์ และเป็นปีอ้างอิงของแนวโน้ม workload/กำลังคน", unit:"พ.ศ.", source:"ปีงบประมาณหรือปีปฏิทินที่ใช้ร่วมกันทั้งชุดข้อมูล", example:"2569", origin:"input" },
    { key:"year-count", title:"จำนวนปี", category:"1. Scenario", aliases:["จำนวนปี"], definition:"จำนวนปีที่ต้องการจำลองต่อเนื่อง ระบบรองรับ 1–10 ปี", unit:"ปี", source:"แผนกำลังคนของหน่วยงาน", example:"5", origin:"input" },
    { key:"province", title:"จังหวัด", category:"2. Scope", aliases:["จังหวัด"], definition:"จังหวัดที่ใช้ดึง baseline ตั้งต้นของประชากร กำลังคน ตำแหน่งว่าง และเกษียณ", unit:"จังหวัด", source:"baseline ในระบบ; ควรตรวจสอบกับข้อมูล HR ล่าสุด", example:"เชียงราย", origin:"input" },
    { key:"district", title:"อำเภอ", category:"2. Scope", aliases:["อำเภอ"], definition:"ชื่ออำเภอของพื้นที่วิเคราะห์ ใช้ระบุขอบเขตงานและรายงาน แต่ไม่ได้กรอง baseline จังหวัดให้อัตโนมัติ", unit:"ชื่อพื้นที่", source:"ผู้ใช้ระบุ", example:"แม่สาย", caution:"หากวิเคราะห์ระดับอำเภอ ต้องแทนค่าประชากรและ workload ด้วยข้อมูลระดับอำเภอจริง", origin:"input" },
    { key:"unit", title:"โรงพยาบาล/หน่วยบริการ", category:"2. Scope", aliases:["โรงพยาบาล/หน่วยบริการ"], definition:"หน่วยบริการเป้าหมายของการจำลอง ใช้ระบุขอบเขตและรายงาน", unit:"ชื่อหน่วยบริการ", source:"ผู้ใช้ระบุ", example:"รพ.แม่สาย", caution:"การพิมพ์ชื่อหน่วยบริการไม่ได้ดึง HIS/HDC ของหน่วยนั้นให้อัตโนมัติ", origin:"input" },
    { key:"scope-mode", title:"ระดับการคำนวณ", category:"2. Scope", aliases:["ระดับการคำนวณ"], definition:"ระบุว่าชุดข้อมูลนี้เป็นระดับจังหวัด อำเภอ โรงพยาบาล หรือเครือข่ายบริการ เพื่อให้การตีความผลถูกขอบเขต", unit:"ระดับพื้นที่", source:"ผู้วิเคราะห์กำหนด", example:"โรงพยาบาล", origin:"input" },
    { key:"population", title:"ประชากรรับผิดชอบ / Service Population", category:"3. Baseline / 5. Need", aliases:["Population","ประชากรรับผิดชอบ/พื้นที่บริการ","Service Population"], definition:"ประชากรที่หน่วยบริการหรือเครือข่ายมีหน้าที่รับผิดชอบจริง ใช้เป็นฐานสร้างค่า workload และ target need", unit:"คน", source:"ทะเบียนประชากร/HDC/ทะเบียนสิทธิ/catchment ตามนิยามที่พื้นที่ตกลง", example:"85,000 คน", caution:"ไม่ควรใช้ประชากรทั้งจังหวัดหากวิเคราะห์เฉพาะอำเภอหรือโรงพยาบาล", origin:"input" },
    { key:"vacancy", title:"Vacancy", category:"3. Baseline / 4. Profession", aliases:["Vacancy","Vacancy ทั้งหมด"], definition:"จำนวนตำแหน่งตามกรอบที่ยังไม่มีผู้ครองตำแหน่ง ณ จุดเวลาอ้างอิง", unit:"ตำแหน่ง/คน", source:"HROPS/HR/กรอบอัตรากำลังล่าสุด", example:"แพทย์ 4 ตำแหน่ง", caution:"โมเดลปัจจุบันใช้ Vacancy เป็นข้อมูลประกอบ ไม่เพิ่ม/ลด Supply อัตโนมัติ ต้องใส่ Recruit/Transfer ตามแผนจริง", origin:"input" },
    { key:"retire5", title:"เกษียณภายใน 5 ปี", category:"3. Baseline / 4. Profession", aliases:["Retire <= 5Y","Retire <=5Y","เกษียณ <=5 ปี ทั้งหมด"], definition:"จำนวนบุคลากรที่คาดว่าจะเกษียณภายใน 5 ปี ใช้เป็นสัญญาณ replacement risk", unit:"คน", source:"ฐาน HR รายบุคคลจากวันเกษียณ", example:"พยาบาล 12 คน", caution:"ค่าที่มีผลต่อ Supply projection คือค่ารายวิชาชีพใน Profession/Supply ไม่ใช่ยอดรวมเพียงอย่างเดียว", origin:"input" },
    { key:"confidence", title:"Confidence", category:"3. Baseline", aliases:["Confidence"], definition:"ระดับความน่าเชื่อถือของชุดข้อมูลที่ผู้ใช้กำหนด: A=verified, B=usable, C=provisional", unit:"A/B/C", source:"การประเมินคุณภาพข้อมูลของทีมงาน", example:"A เมื่อ reconcile HR กับหน่วยบริการแล้ว", caution:"Confidence เป็น metadata เพื่อบอกคุณภาพข้อมูล ปัจจุบันไม่เปลี่ยนผลสูตรคำนวณ", origin:"input" },
    { key:"wisn-mode", title:"WISN Standard Mode", category:"4. Profession", aliases:["WISN Standard Mode"], definition:"ชุดเวลามาตรฐานต่อกิจกรรมที่ใช้แปลง workload เป็นเวลางานรวม; default ใช้ค่าตั้งต้น, High complexity เพิ่ม 10%, Custom ให้กำหนดเอง", unit:"โหมด", source:"ค่าตั้งต้น หรือ time-motion/expert consensus/service standard", example:"Custom standards เมื่อมี time-motion study", caution:"ก่อนใช้ตัดสินใจเชิงนโยบายควรแทนค่า default ด้วยมาตรฐานที่ตรวจสอบแล้ว", origin:"assumption" },
    { key:"current-headcount", title:"Current headcount", category:"4. Profession / 6. Supply", aliases:["Current headcount","Current"], definition:"จำนวนบุคลากรที่ปฏิบัติงานอยู่จริง ณ ปีฐาน ก่อนรับเข้าและออก", unit:"คน", source:"HROPS/HRIS/บัญชีกำลังคนจริง", example:"แพทย์ 18 คน", origin:"input" },
    { key:"awt", title:"AWT — Available Working Time", category:"4. Profession", aliases:["AWT min/year"], definition:"เวลาทำงานที่มีให้จริงต่อบุคลากร 1 FTE ต่อปี หลังหักวันหยุด ลา อบรม และเวลาที่ไม่พร้อมให้บริการตามนิยาม WISN", unit:"นาที/คน/ปี", source:"ปฏิทินราชการ + ข้อมูลลา/อบรม หรือมาตรฐานองค์กร", example:"90,720 นาที = 210 วัน × 7.2 ชม. × 60", caution:"ระบบใช้ 90,720 นาทีเป็นค่าเริ่มต้น ควรตรวจสอบกับบริบทจริง", origin:"assumption" },
    { key:"cas", title:"CAS support %", category:"4. Profession", aliases:["CAS support %"], definition:"Category Allowance Standard: สัดส่วนเวลาสำหรับกิจกรรมสนับสนุนที่บุคลากรทุกคนในวิชาชีพนั้นทำ เช่น ประชุม บันทึกงาน งานบริหารทั่วไป", unit:"% เวลาทำงาน", source:"time-motion/work sampling/consensus", example:"14%", caution:"ระบบใช้ CAF = 1/(1-CAS%) ดังนั้น CAS สูงขึ้นจะทำให้ Required FTE สูงขึ้น", origin:"assumption" },
    { key:"ias", title:"IAS hours/year", category:"4. Profession", aliases:["IAS hours/year"], definition:"Individual Allowance Standard: ชั่วโมงกิจกรรมเพิ่มเติมของบุคลากรบางราย ไม่ใช่ทุกคน เช่น งานหัวหน้ากลุ่ม/คณะกรรมการเฉพาะ", unit:"ชั่วโมง/ปี", source:"ภาระงานจริง/คำสั่งมอบหมาย/การสำรวจเวลา", example:"40 ชั่วโมง/ปี", caution:"ระบบใช้ IAF = IAS ชั่วโมง × 60 / AWT แล้วบวกเข้า Required FTE", origin:"assumption" },
    { key:"activity-standard", title:"Activity Standard", category:"4. Profession", aliases:["Activity Standards (minutes per case)"], definition:"เวลามาตรฐานที่วิชาชีพหนึ่งใช้ต่อกิจกรรมบริการ 1 หน่วย เป็นตัวเชื่อม workload กับความต้องการกำลังคน", unit:"นาที/ครั้ง หรือ นาที/case", source:"time-motion study/expert consensus/service standard", example:"แพทย์ OPD 8 นาที/visit", caution:"ควรเป็นเวลาของวิชาชีพนั้นต่อหน่วยบริการ ไม่ใช่เวลารวมทั้งทีม", origin:"assumption" },
    { key:"opd", title:"OPD Visits / OPD", category:"5. Workload", aliases:["OPD","OPD Visits"], definition:"จำนวนครั้งรับบริการผู้ป่วยนอกทั้งหมดใน 1 ปีตามขอบเขตที่เลือก", unit:"visits/ปี", source:"HIS/HDC/รายงานบริการที่ตรวจสอบแล้ว", example:"120,000 visits/ปี", origin:"input" },
    { key:"ipd", title:"IPD Admits", category:"5. Workload", aliases:["IPD Admit","IPD Admits"], definition:"จำนวนครั้งรับไว้รักษาเป็นผู้ป่วยในต่อปี", unit:"admissions/ปี", source:"HIS/IPD census/DRG", example:"6,500 admissions/ปี", origin:"input" },
    { key:"er", title:"ER Visits", category:"5. Workload", aliases:["ER","ER Visits"], definition:"จำนวนครั้งรับบริการห้องฉุกเฉินต่อปี", unit:"visits/ปี", source:"HIS ER/EMS-ER report", example:"18,000 visits/ปี", origin:"input" },
    { key:"procedure", title:"OR / Procedure", category:"5. Workload", aliases:["OR/Procedure"], definition:"จำนวนหัตถการหรือการผ่าตัดที่อยู่ในขอบเขตงานของวิชาชีพที่วิเคราะห์", unit:"cases/ปี", source:"OR log/procedure registry/HIS", example:"2,400 cases/ปี", caution:"กำหนดนิยามให้คงที่ เช่น นับเฉพาะ OR หรือรวม minor procedure", origin:"input" },
    { key:"delivery", title:"Delivery", category:"5. Workload", aliases:["Delivery"], definition:"จำนวนการคลอดที่หน่วยบริการดูแลต่อปี", unit:"deliveries/ปี", source:"ห้องคลอด/HIS", example:"850 ราย/ปี", origin:"input" },
    { key:"chronic", title:"Chronic Visits", category:"5. Workload", aliases:["Chronic","Chronic Visits"], definition:"จำนวนครั้งบริการกลุ่มโรคเรื้อรัง เช่น DM/HT/CKD ตามนิยามพื้นที่", unit:"visits/ปี", source:"HIS/HDC/NCD registry", example:"35,000 visits/ปี", origin:"input" },
    { key:"mental", title:"Mental Visits", category:"5. Workload", aliases:["Mental","Mental Visits"], definition:"จำนวนครั้งบริการสุขภาพจิต/จิตเวช/สารเสพติดตามขอบเขตที่กำหนด", unit:"visits/ปี", source:"HIS/mental health registry", example:"4,200 visits/ปี", origin:"input" },
    { key:"outreach", title:"Outreach / PP", category:"5. Workload", aliases:["Outreach/PP"], definition:"กิจกรรมเชิงรุก/ส่งเสริมป้องกัน/เยี่ยมบ้าน/ชุมชนที่ใช้เวลาบุคลากร", unit:"visits หรือกิจกรรม/ปี", source:"ระบบ PP/HDC/ทะเบียนเยี่ยมบ้าน", example:"12,000 contacts/ปี", caution:"หน่วยนับต้องสอดคล้องกับ Activity Standard", origin:"input" },
    { key:"complexity", title:"Complexity", category:"5. Workload", aliases:["Complexity","Need Complexity"], definition:"ตัวคูณความซับซ้อนของภาระงาน; 1.00=มาตรฐาน, มากกว่า 1=ใช้ทรัพยากร/เวลามากขึ้น", unit:"ดัชนี", source:"case-mix/acuity/referral complexity/consensus", example:"1.20 = ภาระงานเทียบเท่าเพิ่ม 20%", caution:"หากไม่มีหลักฐานควรใช้ 1.00 เพื่อหลีกเลี่ยงการเพิ่ม need ซ้ำซ้อน", origin:"assumption" },
    { key:"target-need", title:"Health Need Group", category:"5. Target Need", aliases:["Health Need Group","Target Need Forecast"], definition:"กลุ่มสุขภาพที่ควรได้รับบริการ แม้บริการจริงต่ำเพราะเข้าไม่ถึงบริการ ใช้ป้องกัน under-service ถูกแปลว่าต้องการคนน้อย", unit:"กลุ่มเป้าหมาย", source:"epidemiology/registry/service plan/population health need", example:"CKD 3–5, trauma, LTC, SMI", origin:"input" },
    { key:"target-pop", title:"Target Population / Cases", category:"5. Target Need", aliases:["Target Population / Cases"], definition:"จำนวนประชากรหรือผู้ป่วยที่ควรอยู่ในกลุ่มเป้าหมายในปีนั้น ก่อนคูณ coverage", unit:"คน/cases", source:"registry/prevalence/incidence/risk stratification", example:"CKD 3–5 = 1,500 คน", origin:"input" },
    { key:"actual-served", title:"Actual Served", category:"5. Target Need", aliases:["Actual Served"], definition:"จำนวนคนในกลุ่มเป้าหมายที่ได้รับบริการจริงในปีนั้น", unit:"คน/cases", source:"registry/HIS/HDC", example:"900 คน", origin:"input" },
    { key:"coverage", title:"Target Coverage %", category:"5. Target Need", aliases:["Target Coverage %"], definition:"สัดส่วนของกลุ่มเป้าหมายที่ควรได้รับบริการตามเป้าหมายนโยบายหรือ service standard", unit:"%", source:"service plan/guideline/target", example:"80%", caution:"สูตรใช้ Target cases = Target population × Coverage%", origin:"input" },
    { key:"frequency", title:"Service Freq / Year", category:"5. Target Need", aliases:["Service Freq / Year"], definition:"จำนวนครั้งบริการเฉลี่ยที่ผู้รับบริการเป้าหมาย 1 คนควรได้รับต่อปี", unit:"ครั้ง/คน/ปี", source:"CPG/service model/consensus", example:"DM uncontrolled 3 ครั้ง/ปี", origin:"input" },
    { key:"placement", title:"Placement", category:"5. Target Need", aliases:["Placement"], definition:"ระดับหน่วยบริการที่เหมาะสมในการรองรับกลุ่ม need ใช้ประกอบการออกแบบเครือข่าย", unit:"ระดับบริการ/ข้อความ", source:"service plan/referral network", example:"รพท./รพช.ใหญ่", caution:"Placement ปัจจุบันไม่เปลี่ยนสูตรอัตโนมัติ", origin:"input" },
    { key:"recruit", title:"Recruit", category:"6. Supply", aliases:["Recruit"], definition:"จำนวนบุคลากรใหม่ที่คาดว่าจะเริ่มปฏิบัติงานในปีนั้น", unit:"คน/ปี", source:"แผนบรรจุ/สรรหา/จัดสรรตำแหน่ง", example:"2 คน", origin:"input" },
    { key:"transfer-in", title:"Transfer In", category:"6. Supply", aliases:["Transfer In"], definition:"จำนวนบุคลากรที่ย้ายหรือโอนเข้ามาในปีนั้น", unit:"คน/ปี", source:"แผน HR/คำสั่งย้าย", example:"1 คน", origin:"input" },
    { key:"return-in", title:"Return In", category:"6. Supply", aliases:["Return In"], definition:"จำนวนบุคลากรที่กลับเข้าปฏิบัติงาน เช่น กลับจากลาศึกษาหรือภารกิจชั่วคราว", unit:"คน/ปี", source:"แผน HR รายบุคคล", example:"2 คน", origin:"input" },
    { key:"retire", title:"Retire", category:"6. Supply", aliases:["Retire"], definition:"จำนวนบุคลากรที่เกษียณออกจากหน่วยในปีนั้น", unit:"คน/ปี", source:"ฐาน HR รายบุคคล", example:"3 คน", origin:"input" },
    { key:"resign", title:"Resign", category:"6. Supply", aliases:["Resign"], definition:"จำนวนบุคลากรที่คาดว่าจะลาออกในปีนั้น", unit:"คน/ปี", source:"ข้อมูลย้อนหลัง/คำขอลาออก/retention model", example:"1 คน", origin:"input" },
    { key:"transfer-out", title:"Transfer Out", category:"6. Supply", aliases:["Transfer Out"], definition:"จำนวนบุคลากรที่ย้ายหรือโอนออกในปีนั้น", unit:"คน/ปี", source:"แผน HR/คำสั่งย้าย", example:"1 คน", origin:"input" },
    { key:"study-leave", title:"Study Leave", category:"6. Supply", aliases:["Study Leave"], definition:"จำนวนบุคลากรที่ออกจากกำลังให้บริการเนื่องจากลาศึกษาตามนิยามหน่วยงาน", unit:"คน/ปี", source:"แผนพัฒนาบุคลากร/คำสั่งลาศึกษา", example:"1 คน", origin:"input" },
    { key:"fte-factor", title:"FTE Factor", category:"6. Supply", aliases:["FTE Factor"], definition:"สัดส่วนกำลังทำงานจริงเทียบกับคนทำงานเต็มเวลา 1 คน", unit:"0–1 โดยทั่วไป", source:"รูปแบบการจ้าง/เวลาปฏิบัติงานจริง", example:"1.0=เต็มเวลา, 0.5=ครึ่งเวลา", caution:"Supply FTE = Projected headcount × FTE Factor", origin:"input" },
    { key:"projected", title:"Projected Headcount", category:"6. Supply", aliases:["Projected"], definition:"จำนวนคนปลายปีหลังรวมการเข้าและออกของปีนั้น", unit:"คน", source:"ระบบคำนวณ", example:"Current + Recruit + Transfer In + Return In - Retire - Resign - Transfer Out - Study Leave", origin:"output" },
    { key:"actual-fte", title:"Actual FTE", category:"7. Results", aliases:["Actual FTE"], definition:"FTE ที่ workload บริการจริงต้องการ ตาม Activity Standard, AWT, CAS และ IAS", unit:"FTE", source:"ระบบคำนวณจาก workload จริง", example:"18.4 FTE", origin:"output" },
    { key:"target-fte", title:"Target FTE", category:"7. Results", aliases:["Target FTE"], definition:"FTE ที่ target health need ต้องการ หากให้บริการตาม population need, coverage และ frequency", unit:"FTE", source:"ระบบคำนวณจาก Target Need", example:"21.2 FTE", origin:"output" },
    { key:"planning-fte", title:"Planning FTE / Required FTE", category:"7. Results", aliases:["Planning FTE","Required FTE"], definition:"กำลังคนสำหรับวางแผน โดยเลือกระดับกิจกรรมที่สูงกว่าระหว่าง workload จริงที่ปรับ complexity กับ target-need activity ในแต่ละกิจกรรม แล้วคำนวณ WISN", unit:"FTE", source:"ระบบคำนวณ", example:"22.1 FTE", caution:"ไม่จำเป็นต้องเท่ากับ max(Actual FTE, Target FTE) ตรง ๆ เพราะเลือก max ราย activity ก่อนรวม", origin:"output" },
    { key:"supply-fte", title:"Supply FTE", category:"7. Results", aliases:["Supply FTE"], definition:"กำลังคนที่คาดว่าจะมีจริงหลังการเคลื่อนไหวบุคลากร และปรับด้วย FTE Factor", unit:"FTE", source:"ระบบคำนวณจาก Supply projection", example:"17.0 FTE", origin:"output" },
    { key:"hr-gap", title:"HR GAP", category:"7. Results", aliases:["HR GAP","Total Positive GAP"], definition:"ส่วนต่าง Required/Planning FTE - Supply FTE", unit:"FTE", source:"ระบบคำนวณ", example:"+5.1 = ขาด 5.1 FTE; -2.0 = supply มากกว่า need 2 FTE", caution:"ค่าบวก=ขาด, ค่าลบ=ส่วนเกินเชิงโมเดล", origin:"output" },
    { key:"wisn-ratio", title:"WISN Ratio", category:"7. Results", aliases:["WISN Ratio"], definition:"Supply FTE ÷ Required FTE ใช้บอกสมดุลกำลังคนเทียบภาระงาน", unit:"ratio", source:"ระบบคำนวณ", example:"1.00=สมดุล, 0.80=มีคน 80% ของที่ต้องการ, 1.20=supply สูงกว่า need 20%", origin:"output" },
    { key:"pressure", title:"Pressure Index", category:"7. Results", aliases:["Pressure"], definition:"Required FTE ÷ Supply FTE เป็นค่ากลับของ WISN ratio ใช้สื่อแรงกดดันภาระงานต่อกำลังคน", unit:"ratio", source:"ระบบคำนวณ", example:"1.25 = ภาระสูงกว่ากำลังคนประมาณ 25%", origin:"output" },
    { key:"trend", title:"Trend", category:"7. Results", aliases:["Trend"], definition:"Required FTE ของปีนั้น ÷ Required FTE ปีฐาน เพื่อดูแนวโน้ม need", unit:"index", source:"ระบบคำนวณ", example:"1.10 = need สูงกว่าปีฐาน 10%", origin:"output" },
    { key:"coverage-gap", title:"Coverage Gap", category:"7. Results", aliases:["Coverage Gap"], definition:"จำนวน target cases ที่ควรได้รับบริการตาม coverage target แต่ยังไม่ได้รับบริการจริง", unit:"คน/cases", source:"ระบบคำนวณ", example:"1,200 - 900 = 300", origin:"output" },
    { key:"workload-gap", title:"Workload Gap", category:"7. Results", aliases:["Workload Gap"], definition:"จำนวนครั้งบริการที่ควรเกิดเพิ่มเพื่อปิด coverage gap ตาม service frequency", unit:"visits/กิจกรรม", source:"ระบบคำนวณ", example:"300 คน × 3 ครั้ง = 900 visits", origin:"output" },
    { key:"suggested-add", title:"Suggested Add", category:"7. Results", aliases:["Suggested Add"], definition:"จำนวน FTE ขั้นต่ำแบบปัดขึ้นที่โมเดลเสนอให้เติมเมื่อ HR GAP เป็นบวก", unit:"คน/FTE โดยประมาณ", source:"ceil(max(HR GAP,0))", example:"GAP 4.2 → 5", caution:"เป็น planning signal ไม่ใช่คำสั่งจัดสรรตำแหน่ง ต้องดูงบประมาณ skill mix และ service design ร่วม", origin:"output" },
    { key:"reallocate", title:"Reallocate", category:"7. Results", aliases:["Reallocate"], definition:"FTE ที่ supply สูงกว่า planning need และอาจพิจารณา rotation/shared service/ปรับการกระจาย", unit:"FTE", source:"max(0,-HR GAP)", example:"GAP -2.3 → 2.3 FTE", caution:"ไม่ควรย้ายคนจากผลนี้เพียงอย่างเดียว ต้องดู competency, access และ minimum staffing", origin:"output" },
    { key:"risk", title:"Risk", category:"7. Results", aliases:["Risk","High Risk Rows"], definition:"ระดับเตือนความเสี่ยงจาก shortage ของโมเดล", unit:"green/yellow/red", source:"เกณฑ์ใน simulator", example:"Red เมื่อ WISN ratio <0.85 หรือ GAP ≥10 FTE หรือ GAP ≥20% ของ need หรือ supply=0 ทั้งที่มี need", origin:"output" },
    { key:"recommendation", title:"Recommendation", category:"7. Results", aliases:["Recommendation"], definition:"ข้อความช่วยตีความจาก gap, retirement, supply trend, coverage gap และ risk เพื่อเริ่มวางแผน", unit:"ข้อความ", source:"rule-based logic ใน simulator", example:"ขาดตาม WISN + เกษียณสูง: ทำ replacement pipeline และ retention", caution:"เป็น heuristic ไม่ใช่ข้อสรุปแทนผู้บริหาร", origin:"output" }
  ];

  const ORIGIN_LABELS={input:"กรอก/ตรวจสอบ",assumption:"ค่าตั้งต้น/สมมติฐาน",output:"ระบบคำนวณ"};
  const byAlias=new Map();
  let activeButton=null, helpVisible=true;
  const normalize=v=>String(v||"").replace(/\s+/g," ").replace(/[?*:]/g,"").trim().toLowerCase();
  HELP_ITEMS.forEach(item=>(item.aliases||[]).forEach(alias=>{const k=normalize(alias);if(!byAlias.has(k))byAlias.set(k,item);}));
  const escapeHtml=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");

  function itemForText(text){const clean=normalize(text);if(byAlias.has(clean))return byAlias.get(clean);for(const [alias,item] of byAlias){if(clean===alias||clean.startsWith(alias+" ")||alias.startsWith(clean+" "))return item;}return null;}
  function createHelpButton(item){const b=document.createElement("button");b.type="button";b.className="hr-help-btn";b.textContent="?";b.setAttribute("aria-label",`คำอธิบาย ${item.title}`);b.dataset.helpKey=item.key;b.setAttribute("aria-expanded","false");return b;}
  function enhanceTextHost(host){if(!host||host.dataset.helpEnhanced==="1"||host.querySelector(":scope > .hr-help-btn"))return;const item=itemForText(host.childNodes[0]?.textContent||host.textContent);if(!item)return;host.dataset.helpEnhanced="1";host.appendChild(createHelpButton(item));}
  function enhanceLabels(){document.querySelectorAll(".field > span,.metric > span,.subsection-head h4,.data-table th").forEach(enhanceTextHost);}
  function addProfessionHelp(){[["[data-prof-current]","current-headcount"],["[data-prof-awt]","awt"],["[data-prof-cas]","cas"],["[data-prof-ias]","ias"],["[data-prof-vacant]","vacancy"],["[data-prof-retire]","retire5"]].forEach(([sel,key])=>document.querySelectorAll(sel).forEach(input=>{const host=input.closest(".field")?.querySelector("span"),item=HELP_ITEMS.find(x=>x.key===key);if(host&&item&&!host.querySelector(".hr-help-btn")){host.dataset.helpEnhanced="1";host.appendChild(createHelpButton(item));}}));}
  function tooltipHtml(item){return `<strong>${escapeHtml(item.title)}</strong><div>${escapeHtml(item.definition)}</div><dl><dt>หน่วย:</dt><dd>${escapeHtml(item.unit||"-")}</dd><dt>แหล่งข้อมูล:</dt><dd>${escapeHtml(item.source||"-")}</dd><dt>ตัวอย่าง:</dt><dd>${escapeHtml(item.example||"-")}</dd></dl>${item.caution?`<div class="hr-help-caution"><b>ข้อควรระวัง:</b> ${escapeHtml(item.caution)}</div>`:""}`;}
  function positionTooltip(button,tip){const r=button.getBoundingClientRect(),m=10,w=Math.min(370,window.innerWidth-24);tip.style.width=`${w}px`;const tr=tip.getBoundingClientRect();let l=r.left+r.width/2-tr.width/2;l=Math.max(12,Math.min(l,window.innerWidth-tr.width-12));let t=r.bottom+m;if(t+tr.height>window.innerHeight-12)t=Math.max(12,r.top-tr.height-m);tip.style.left=`${l}px`;tip.style.top=`${t}px`;}
  function showTooltip(button){const item=HELP_ITEMS.find(x=>x.key===button.dataset.helpKey),tip=document.getElementById("hrHelpTooltip");if(!item||!tip)return;if(activeButton&&activeButton!==button)activeButton.setAttribute("aria-expanded","false");activeButton=button;button.setAttribute("aria-expanded","true");tip.innerHTML=tooltipHtml(item);tip.classList.add("visible");positionTooltip(button,tip);}
  function hideTooltip(){const tip=document.getElementById("hrHelpTooltip");if(tip)tip.classList.remove("visible");if(activeButton)activeButton.setAttribute("aria-expanded","false");activeButton=null;}

  function injectStartGuide(){if(document.getElementById("hrHelpStart"))return;const topbar=document.querySelector(".topbar");if(!topbar)return;const guide=document.createElement("section");guide.className="hr-help-start";guide.id="hrHelpStart";guide.innerHTML=`<div class="hr-help-start__head"><div><h3>เริ่มใช้งาน: เตรียมข้อมูล 6 ชุดนี้ก่อนคำนวณ</h3><p>ไม่แน่ใจว่าช่องไหนหมายถึงอะไร ให้วางเมาส์หรือแตะปุ่ม <b>?</b> ข้างชื่อข้อมูล เพื่อดูนิยาม หน่วย แหล่งข้อมูล และตัวอย่าง</p></div><div class="hr-help-actions"><button class="btn secondary" type="button" id="hrOpenDictionary">คู่มือข้อมูล / Data Dictionary</button><button class="btn ghost" type="button" id="hrToggleHelp">ซ่อนปุ่ม ?</button></div></div><div class="hr-help-steps"><div class="hr-help-step"><strong>1. ขอบเขต</strong><span>จังหวัด → อำเภอ → รพ./เครือข่าย</span></div><div class="hr-help-step"><strong>2. Baseline</strong><span>ประชากร กำลังคน ตำแหน่งว่าง เกษียณ</span></div><div class="hr-help-step"><strong>3. วิชาชีพ</strong><span>Current, AWT, CAS, IAS, time standard</span></div><div class="hr-help-step"><strong>4. Workload + Need</strong><span>บริการจริง + กลุ่มที่ควรได้รับบริการ</span></div><div class="hr-help-step"><strong>5. Supply</strong><span>รับเข้า ย้ายเข้า/ออก เกษียณ ลาออก ลาศึกษา</span></div><div class="hr-help-step"><strong>6. อ่านผล</strong><span>GAP, WISN ratio, pressure, risk</span></div></div><div class="hr-help-notice"><b>สำคัญ:</b> ค่า workload และ target need บางช่องถูกสร้างเป็นค่าเริ่มต้นจากสมมติฐานของ simulator เพื่อให้ทดลองระบบได้ ก่อนใช้วางแผนจริงควรแทนด้วยข้อมูล HIS/HDC/HR และนิยามที่พื้นที่รับรอง</div>`;topbar.insertAdjacentElement("afterend",guide);}
  function injectSectionNotes(){const notes={baseline:"<b>Baseline จังหวัดเป็นเพียงจุดตั้งต้น:</b> ถ้าวิเคราะห์ระดับอำเภอหรือโรงพยาบาล ให้แทน Population/Vacancy/Retirement ด้วยข้อมูลของพื้นที่จริง",profession:"<b>AWT/CAS/IAS และ Activity Standard มีผลต่อ Required FTE โดยตรง:</b> หากยังไม่มี time-motion ให้ใช้ default เพื่อจำลองเบื้องต้นและระบุ Assumption ให้ชัด",need:"<b>Workload จริง ≠ Health need:</b> บริการต่ำอาจเกิดจากเข้าไม่ถึงบริการ จึงมี Target Need เพื่อไม่ให้ under-service ถูกแปลว่าต้องการคนน้อย",supply:"<b>Supply ต้องใส่เป็นเหตุการณ์รายปี:</b> Vacancy ไม่ได้กลายเป็น Recruit อัตโนมัติ ให้ใส่เฉพาะคนที่มีแผนว่าจะเข้าหรือออกจริง",results:"<b>อ่าน HR GAP ก่อน:</b> ค่าบวก = ขาด, ค่าลบ = supply สูงกว่า need; WISN ratio < 1 หมายถึงกำลังคนต่ำกว่าความต้องการ"};Object.entries(notes).forEach(([id,html])=>{const s=document.getElementById(id),h=s?.querySelector(".panel-header");if(s&&h&&!s.querySelector(".hr-help-section-note")){const n=document.createElement("div");n.className="hr-help-section-note";n.innerHTML=html;h.insertAdjacentElement("afterend",n);}});}
  function injectTooltip(){if(document.getElementById("hrHelpTooltip"))return;const t=document.createElement("div");t.id="hrHelpTooltip";t.className="hr-help-tooltip";t.setAttribute("role","tooltip");document.body.appendChild(t);}
  function injectDictionary(){if(document.getElementById("hrHelpModal"))return;const m=document.createElement("div");m.className="hr-help-modal";m.id="hrHelpModal";m.setAttribute("aria-hidden","true");m.innerHTML=`<div class="hr-help-dialog" role="dialog" aria-modal="true" aria-labelledby="hrHelpTitle"><div class="hr-help-dialog__head"><div><h2 id="hrHelpTitle">Data Dictionary — HR Blueprint WISN</h2><p>นิยาม • หน่วย • แหล่งข้อมูล • ตัวอย่าง • ข้อควรระวัง</p></div><button type="button" class="hr-help-close" id="hrHelpClose" aria-label="ปิด">×</button></div><div class="hr-help-search"><input id="hrHelpSearch" type="search" placeholder="ค้นหา เช่น AWT, Vacancy, WISN ratio, OPD, Coverage..."></div><div class="hr-help-list" id="hrHelpList"></div></div>`;document.body.appendChild(m);const f=document.createElement("button");f.type="button";f.className="hr-help-floating";f.id="hrHelpFloating";f.textContent="? คู่มือข้อมูล";document.body.appendChild(f);}
  function renderDictionary(q=""){const l=document.getElementById("hrHelpList");if(!l)return;const n=normalize(q),items=HELP_ITEMS.filter(i=>!n||normalize([i.title,i.category,i.definition,i.unit,i.source,i.example,...(i.aliases||[])].join(" ")).includes(n));l.innerHTML=items.length?items.map(i=>`<article class="hr-help-entry"><div><h3>${escapeHtml(i.title)}</h3><span class="hr-help-entry__tag">${escapeHtml(i.category)}</span><span class="hr-help-origin ${i.origin||"input"}">${escapeHtml(ORIGIN_LABELS[i.origin]||ORIGIN_LABELS.input)}</span></div><div><p>${escapeHtml(i.definition)}</p><p><b>หน่วย:</b> ${escapeHtml(i.unit||"-")}</p><p><b>แหล่งข้อมูล:</b> ${escapeHtml(i.source||"-")}</p><p><b>ตัวอย่าง:</b> ${escapeHtml(i.example||"-")}</p>${i.caution?`<p><b>ข้อควรระวัง:</b> ${escapeHtml(i.caution)}</p>`:""}</div></article>`).join(""):`<div class="hr-help-empty">ไม่พบคำที่ค้นหา</div>`;}
  function openDictionary(){const m=document.getElementById("hrHelpModal");if(!m)return;hideTooltip();renderDictionary(document.getElementById("hrHelpSearch")?.value||"");m.classList.add("open");m.setAttribute("aria-hidden","false");setTimeout(()=>document.getElementById("hrHelpSearch")?.focus(),0);}
  function closeDictionary(){const m=document.getElementById("hrHelpModal");if(!m)return;m.classList.remove("open");m.setAttribute("aria-hidden","true");}
  function toggleHelp(){helpVisible=!helpVisible;document.body.classList.toggle("hr-help-off",!helpVisible);const b=document.getElementById("hrToggleHelp");if(b)b.textContent=helpVisible?"ซ่อนปุ่ม ?":"แสดงปุ่ม ?";if(!helpVisible)hideTooltip();}
  function bindHelpEvents(){document.addEventListener("mouseover",e=>{const b=e.target.closest(".hr-help-btn");if(b&&helpVisible)showTooltip(b);});document.addEventListener("focusin",e=>{const b=e.target.closest(".hr-help-btn");if(b&&helpVisible)showTooltip(b);});document.addEventListener("click",e=>{const b=e.target.closest(".hr-help-btn");if(b){e.preventDefault();e.stopPropagation();activeButton===b?hideTooltip():helpVisible&&showTooltip(b);return;}if(!e.target.closest("#hrHelpTooltip"))hideTooltip();});document.getElementById("hrOpenDictionary")?.addEventListener("click",openDictionary);document.getElementById("hrHelpFloating")?.addEventListener("click",openDictionary);document.getElementById("hrHelpClose")?.addEventListener("click",closeDictionary);document.getElementById("hrToggleHelp")?.addEventListener("click",toggleHelp);document.getElementById("hrHelpSearch")?.addEventListener("input",e=>renderDictionary(e.target.value));document.getElementById("hrHelpModal")?.addEventListener("click",e=>{if(e.target.id==="hrHelpModal")closeDictionary();});document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeDictionary();hideTooltip();}});window.addEventListener("resize",()=>{if(activeButton){const t=document.getElementById("hrHelpTooltip");if(t?.classList.contains("visible"))positionTooltip(activeButton,t);}});window.addEventListener("scroll",hideTooltip,true);}
  function observeDynamicContent(){const o=new MutationObserver(()=>{enhanceLabels();addProfessionHelp();});["professionGrid","standardTable","needTable","targetNeedTable","supplyTable","resultTable"].forEach(id=>{const n=document.getElementById(id);if(n)o.observe(n,{childList:true,subtree:true});});}
  function bootHelp(){injectStartGuide();injectSectionNotes();injectTooltip();injectDictionary();enhanceLabels();addProfessionHelp();renderDictionary();bindHelpEvents();observeDynamicContent();}
  document.readyState==="loading"?document.addEventListener("DOMContentLoaded",bootHelp):bootHelp();
})();
